2 try to docker deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,7 +34,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Download JAR Artifact
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v3
         with:
           name: app-jar
           path: build/libs
@@ -56,8 +56,14 @@ jobs:
         run: |
           docker run -d -p 8080:8080 --name testing-container testing-app
 
-          sleep 5
-          curl --retry 5 --retry-delay 5 --max-time 30 http://localhost:8080 || { echo "Application failed to start"; exit 1; }
+          echo "Waiting for 15 seconds for the application to start..."
+          sleep 15
+
+          curl --retry 5 --retry-delay 5 --max-time 30 http://localhost:8080 || { 
+            echo "Application failed to start. Fetching logs..."; 
+            docker logs testing-container; 
+            exit 1; 
+          }
 
       - name: Wait for 1 minute
         run: |
